
### Get articles of a specific userId
GET http://localhost:3001/articles?userId=fc5c4e4a-0cb6-420b-9268-8fed8dd7d51c

### Get Article by Id
GET http://localhost:3001/articles/4

### Create Article
POST http://localhost:3001/articles
Content-Type: application/json

{
    "title": "Last test",
    "content": "content-test",
    "created_at": "2024-01-17T12:00:00Z",
    "date": "2025-02-03T23:25:16Z",
    "author": "author-test",
    "subtitle": "subtitle-test",
    "featured_image": "https://m-cdn.phonearena.com/images/article/167259-wide-two_1200/Galaxy-S26-Ultra-camera-rumor-making-the-Galaxy-S25-Ultra-look-outdated-already.jpg",
    "topics": ["News"],
    "urlsegment": "galaxy-s26-ultra-camera-rumor-making-the-galaxy-s25-ultra-look-outdated-already---phonearena",
    "original_url": "https://www.phonearena.com/news/Galaxy-S26-Ultra-camera-rumor-making-the-Galaxy-S25-Ultra-look-outdated-already_id167259",
    "user_id": "fc5c4e4a-0cb6-420b-9268-8fed8dd7d51c",
    "questions_and_answers": []
}

### Update Article
PUT http://localhost:3001/articles/4
Content-Type: application/json

{
    "questions_and_answers": [

        {
            "answer": "44Test Question",
            "question": "44Test Answer"
        }
    ]
}

### Delete Article
DELETE http://localhost:3001/articles/2
Content-Type: application/json



###### Test
GET http://localhost:3001/error-test